#!/bin/bash
echo "=> Building the binary"
docker run --rm --name my-maven-project -v "$(pwd)":/usr/src/mymaven -w /usr/src/mymaven maven:3.3-jdk-8 /bin/bash -c " mvn install:install-file -Dfile=bc-fips/bc-fips-1.0.0.jar -DgroupId=org-bouncycastle -DartifactId=bc-fips -Dversion=1.0.0 -Dpackaging=jar && mvn clean install"